name: mo8tarib
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7
  flare_flutter: ^2.0.1
  font_awesome_flutter: ^8.8.1
  flutter_bloc: ^6.0.1
  flutter_awesome_buttons: ^0.1.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.17.0
  cached_network_image: ^2.2.0+1
  provider: ^4.3.1
  flutter_facebook_login: ^1.2.0
  google_sign_in: ^4.5.1
  bubble_bottom_bar: ^1.2.0
  flutter_rating_bar: ^3.0.1+1
  date_range_picker: ^1.0.6
  intl: ^0.16.1
  carousel_pro: ^1.0.0
  image_picker: ^0.6.7+4
  path: ^1.6.4
  firebase_storage: ^3.1.5
  image_downloader: ^0.19.2
  geolocator: ^5.1.3
  bubble_tab_indicator: ^0.1.4








dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - lang/fr.json
    - assets/images/
    - images/


  fonts:
   - family: Pacifico
     fonts:
       - asset: fonts/Pacifico-Regular.ttf
   - family: VarelaRound
     fonts:
       - asset: fonts/VarelaRound-Regular.ttf

